#!/usr/bin/env bash
set -e
URL="https://docs.aws.amazon.com/config/latest/developerguide"

curl -X GET -s "${URL}/managed-rules-by-aws-config.html" | grep "<p><a href=\"./" | grep .html | awk -F'./' '{print$2}' | awk -F'">' '{print$1}' > rules.txt

for i in $(cat rules.txt)
do
  IDENTIFIER=$(curl -X GET -s "${URL}"/"${i}" | grep "<b>Identifier:" | awk -F'</b> ' '{print $2}')
  TRIGGER=$(curl -X GET -s "${URL}"/"${i}" | grep "<b>Trigger" | awk -F'</b> ' '{print $2}')
  PARAMETERS=$(curl -X GET -s "${URL}"/"${i}" | sed -n -e '/<b>Parameters:/,/AWS CloudFormation template/ p' | grep "span class=\"term\"" | awk -F'\"term\"> ' '{print $2}' | awk -F' </' '{print $1}')
  NAME="${i//.html/}"

  printf "\"${NAME}\": {\n"
  printf "\t\"name\": \"$NAME\",\n"
  printf "\t\"description\": \"Config rule, generated by terraform\",\n"
  printf "\t\"source_identifier\": \"${IDENTIFIER}\",\n"
  printf "\t\"parameters\": "
  printf "\""
  PARAM=""
    if [ $(echo ${PARAMETERS} | wc -w) -gt 0 ]
    then
      PARAM="{"
      for x in ${PARAMETERS}
      do
        PARAM=${PARAM}"\\\\\"${x}\\\\\": \\\\\"\\\\\", "
      done
      PARAM=${PARAM}"}"
    fi
    PARAM=$(echo "${PARAM}" | sed 's/, }/}/' | grep -v "None")
    printf "${PARAM}"
    printf "\""
  printf "\n},\n"

done
